name: DevSecOps IaC Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    name: Infrastructure Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init & Validate
        run: |
          cd terraform
          terraform init
          terraform validate

      # This runs the Checkov security tool against our code
      - name: Run Checkov Security Scanner
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          directory: terraform/
          soft_fail: false
          output_format: cli
          # This skips the advanced enterprise logging/replication rules you are seeing
          skip_check: CKV_AWS_144,CKV_AWS_145,CKV2_AWS_61,CKV2_AWS_62,CKV2_AWS_11,CKV2_AWS_12,CKV2_AWS_5